### ISSUE TITLE
Nav buttons on cache display do not delete when cache level is removed

### ISSUE THREAD

**Issue by kevinsrose** [Ctrl-Alt-Delicious/CacheSimulator#115]
Steps to reproduce:
1. Start the app and add 2 or 3 cache levels
2. Delete the L2 and/or L3
3. The top nav bar still shows the buttons for L2 and L3 and user is still able to access those cache details

**Comment by jbonzo** [comment]
It does not. its not a bug i was trying to fix. you're all good.
