### ISSUE TITLE
Highlight rows in memory access queue based on the current simulation step

### ISSUE THREAD

**Issue by kevinsrose** [Ctrl-Alt-Delicious/CacheSimulator#17]
One row of the memory access queue should be highlighted reflecting the current position of the simulation

**Comment by ryan-berst** [comment]
At the moment, there is no "current simulation step" since there is no BE.
I'm implementing row highlighting functionality that will respond to clicks. Once we have the BE, we can remove `ng-click`.

**Comment by jbonzo** [comment]
What's a BE?

**Comment by jbonzo** [comment]
oh backend..
