### ISSUE TITLE
Scaling for Lower Resolution Displays

### ISSUE THREAD

**Issue by ryan-berst** [Ctrl-Alt-Delicious/CacheSimulator#36]
When viewing on a display that is 1280 x 720, the user is currently required to scroll down to see the L3. I believe this is related to the lack of scaling in the side-bar, which is fine, but the canvas seems to inherit from it.

Users with 720p displays should be able to view the cache display all at once.

**Comment by kevinsrose** [comment]
This is pretty much being taken care of with issue #88
